### PR TITLE
Fixes issue #1 :Added Colour Picker to select different colours

### LINKED ISSUE #1: Create a color picker dialog box for selecting brush color.
Suggest a color third party lib for implementing this feature.  

You can use this library https://github.com/jaredrummler/ColorPicker

### PR DESCRIPTION
**Pull request by Smarshal21**
Fix #1 
Added Colour Picker dialog to select different colours and paint using those colours
Screenshot_1665142902
Screenshot_1665142877
Screenshot_1665142882

### CODE REVIEW

**Comment by Smarshal21** [comment]
@rishidyno can you please review this PR

**Comment by rishidyno** [comment]
@Smarshal21 reviewed.
Always keep these things in mind.

- Give meaningful branch names.
- Always add EOL
- Learn and Remember to link Issue to PR.
- Always reply to reviews.

@RockingRishav Same for you.

**Comment by Smarshal21** [comment]
@rishidyno can you please review this PR

**Comment by rishidyno** [comment]
LGTM.

**Pull request merged**
