### PR TITLE
#FIX:2 Make a slider for selecting different brush size.

### PR DESCRIPTION
**Pull request by Smarshal21**
i have included few more brush sizes and added them two a scroll view improving the Ui
Screenshot_20221002_141410
This is the UI change representing the increased no of brushes sizes and scroll view

### CODE REVIEW

**Comment by rishidyno** [comment]
@Smarshal21 please add screenshots. And also add EOL to each file changed

**Comment by Smarshal21** [comment]
> @Smarshal21 please add screenshots. And also add EOL to each file changed

@rishidyno code screenshots or the end app screenshots??

**Comment by rishidyno** [comment]
> > @Smarshal21 please add screenshots. And also add EOL to each file changed
> 
> @rishidyno code screenshots or the end app screenshots??

Screenshots for changed or new app UI.

**Comment by Smarshal21** [comment]
> > > @Smarshal21 please add screenshots. And also add EOL to each file changed
> > 
> > 
> > @rishidyno code screenshots or the end app screenshots??
> 
> Screenshots for changed or new app UI.

@rishidyno i have updated the screenshots with changed UI

**Comment by rishidyno** [comment]
@Smarshal21 Thanks for your efforts, but we are not planning on doing it like this. Actually, we want to have a horizontal slider like we have for volume button. 

A dialog box should appear, when clicked on select brush size option icon, where we can see our color's brush size in circular form and real-time brush size changes should be visible to the user while sliding the slider.
If you feel like we can use some third party library for this, please add it in comments, and we can decide whether to proceed with it.

If you still have problem understanding or need more clarification, please let me know.

**Comment by rishidyno** [comment]
image
Like you can take some idea how we want for it to be implemented 
When we change the slider, the value also changes. So this is what we are looking forward for.

**Comment by Smarshal21** [comment]
@rishidyno can i use this continuous slider
https://material.io/components/sliders/android#theming-sliders

**Comment by rishidyno** [comment]
> @rishidyno can i use this continuous slider https://material.io/components/sliders/android#theming-sliders

Yes, I think this works for our project. So green light from my side. You can use this and start implementing. Thanks, @Smarshal21 
Feel free to ask any doubts.

**Pull request closed without merging**
