### PR TITLE
Fixes issue #1 : Added Slider for selecting different brush size

### PR DESCRIPTION
**Pull request by Smarshal21**
@yash10019coder @rishidyno  i have successfully made a slider for selecting different brush size
WhatsApp Image 2022-10-06 at 5 48 57 PM (1)

https://user-images.githubusercontent.com/99678760/194384647-0b9b6a03-7fda-44ca-a949-d6f918bace49.mp4

WhatsApp Image 2022-10-06 at 5 48 57 PM

### CODE REVIEW

**Comment by rishidyno** [comment]
@Smarshal21 Please add a video demonstrating the above implementation. The video should show the changes in brush size. Can you also update me on the range of the brush size?

**Comment by Smarshal21** [comment]
Okay i will do that. I have to check on the range of slider

**Comment by Smarshal21** [comment]
> @Smarshal21 Please add a video demonstrating the above implementation. The video should show the changes in brush size. Can you also update me on the range of the brush size?

i have added the video demonstration sir

**Comment by rishidyno** [comment]
@Smarshal21 this mostly looks good to me, all I want for you to do is, when we want to re-change the brush size the brush pointer should be at the current brush size not at the beginning every time.

Also, You need to resolve your merge conflicts.

**Comment by rishidyno** [comment]
Also, the brush size is not visible, please improve the UI.

image

**Pull request closed without merging**
